global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "forgemind-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["forgemind-api:8000"]
        labels:
          service: "forgemind-ai"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
        labels:
          service: "kafka"
